---
name: Add pull request Cmt

on:
  pull_request:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read

jobs:
  add-pr-cmt:
    uses: vyos/.github/.github/workflows/add-pr-comment.yml@feature/check-pr-commenting
    secrets: inherit
