name: Check for unused imports using Pylint
on:
  pull_request_target:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read

jobs:
  check-unused-imports:
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@T6789-unused-import-checkout-curre
    secrets: inherit
